apiVersion: v2
description: Divorce - Decree Nisi
name: div-dn
version: 2.0.21
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
  - name: redis
    version: 20.13.2
    repository: 'oci://registry-1.docker.io/bitnamicharts'
    tags:
      - pr
  - name: idam-pr
    version: 2.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
    tags:
      - idam-pr
