environment: development
NODE_ENV: development

node:
  port: 3000
  baseUrl: https://localhost:3000

session:
  secret: sessionSecret
  secure: true
  expires: 3600000 # 60 minutes

ssl:
  hpkp:
    maxAge: 3600
    sha256s: AbCdEf123=
    sha256sBackup: ZyXwVu456=

health:
  timeout: 10000
  deadline: 15000

service:
  name: 'divorce-decree-nisi-frontend'

services:
  redis:
    url: redis://127.0.0.1:6379
    useSSL: false
    encryptionAtRestKey: encryptionAtRestKey
  idam:
    apiHealth: https://localhost:8001/health
    authenticationHealth: https://localhost:3000/health
    apiUrl: http://localhost:8001
    secret: '123456'
    loginUrl: https://localhost:3000/idam-mock-login
    clientId: 'divorce'
    proxy:
  saucelabs:
    browser: 'chrome'
    username: 'username'
    key: 'privatekey'
    tunnelId: ''
    waitForTimeout: 30000
  googleAnalytics:
    id: TBD
    trackingUrl: https://localhost:3000/
  applicationInsights:
    instrumentationKey: 'dummy-key'
  evidenceManagmentClient:
    url: http://localhost:4009
    health: http://localhost:4009/status/health
    uploadEndpoint: /emclientapi/version/1/uploadFiles
  rateLimiter:
    total: 3600 # 1 req/s on average per hour
    expire: 3600000
    enabled: false
  orchestrationService:
    getCaseUrl: http://localhost:3001/retrieve-case
    submitCaseUrl: http://localhost:3001/submit-dn
    health: http://localhost:3001/health
    draftEndpoint: http://localhost:3001/draftsapi/version/1
  petitionerFrontend:
    url: https://localhost:8080
    landing: /authenticated
  aosFrontend:
    url: https://localhost:2000
    landing: /authenticated
  caseMaintenance:
    baseUrl: http://localhost:3001/case-maintenance

paths:
  adulteryFirstFoundOut: /first-find-out
  applyForDecreeNisi: /continue-with-divorce
  authenticated: /authenticated
  behaviourContinuedSinceApplication: /behaviour-continued-since-application
  checkYourAnswers: /check-your-answers
  claimCosts: /claim-costs
  done: /done
  entry: /entry
  exit: /exit
  exitIntolerable: /exit/intolerable
  health: /health
  index: /
  intolerable: /intolerable
  livedApartSinceAdultery: /lived-apart-since-adultery
  livedApartSinceDesertion: /lived-apart-since-desertion
  livedApartSinceLastIncidentDate: /lived-apart-since-last-incident-date
  livedApartSinceSeparation: /lived-apart-since-separation
  miniPetition: /review-your-petition
  reviewAosResponse: /review-aos-response
  dnNoResponse: /dn-no-response
  shareCoreDocuments: /share-court-documents
  petitionProgressBar: /progress-bar/petitioner
  upload: /upload-docs
  exitNoCase: /exit-no-case
  termsAndConditions: /terms-and-conditions
  cookiesPolicy: /cookie
  privacyPolicy: /privacy-policy
  contactDivorceTeam: /contact-your-divorce
  amendApplication: /amend-application
  respNotAdmitAdultery: /resp-does-not-admit-adultery-options 
  mock:
    idamLogin: /idam-mock-login
    modifySession: /session

tests:
  functional:
    waitForTimeout: 10000
    waitForAction: 1000
    smartWait: 5000
    outputDir: ../../functional-output
    proxy: http://proxyout.reform.hmcts.net:8080
    proxyByPass: '*beta*LB.reform.hmcts.net'
    idam:
      idamTestUsername:
      idamTestPassword:
      idamTestForename:
      idamTestSurname:
      idamTestUserGroup:
      idamTestLevelOfAccess:
      idamTestSupportCreateAccountEndpoint:

features:
  idam: false
  release520: false

journey:
  timeoutDelay: 300

ccd:
  d8States:
    - 'AwaitingPayment'
  courts:
    - 'serviceCentre'
